### ISSUE TITLE
Does it support 4 x RJ45 by Marvell 88E1543 for 4 ports GbE (x722 series)?

### ISSUE THREAD

**Issue by crazyhulk** [dmarion/i40e#1]
Does it support 4 x RJ45 by Marvell 88E1543 for 4 ports GbE (x722 series)?

If support, I want to make it works for macOS.

**Comment by qianyi98** [comment]
X722MAX支持macos吗？如果支持可以分享一下驱动吗？大佬

**Comment by dmarion** [comment]
wrong place to ask, this is just mirror of intel driver.
